### create payment
POST http://localhost:8000/create-payment

{
  "order_id": "{{$guid}}",
  "amount": 10,
  "customer": {
    "first_name": "John",
    "last_name": "Doe",
    "phone": "0878248219493",
    "email": "john@doe.com"
  },
  "description": "lorem ipsum dolor sit consecti"
}


# FIXME: this is still returning 404 transaction id not found
### get order
@order_id = 6f1cf3b3-7f07-4e4a-945a-754f399595d7
GET http://localhost:8000/transaction/{{order_id}}